title: CRDDS Workshop Materials
description: Slides and other material from CRDDS workshops. 
theme: just-the-docs

url: https://cu-boulder-crdds.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
